### ISSUE TITLE
Not working on the android phones like Samsung Galaxy S4

### ISSUE THREAD

**Issue by khyamay** [driftyco/ionic-example-cordova-camera#3]
This example seems to be working on the android emulator but not on the android device itself. Is it because of the issues with Cordova camera plugins??

**Comment by Ionitron** [comment]
Greetings @khyamay!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
