### ISSUE TITLE
Not saving to device

### ISSUE THREAD

**Issue by krismp** [driftyco/ionic-example-cordova-camera#4]
$scope.getPhoto = function() {
    console.log('Getting camera');

    var options = {
      quality: 75,
      targetWidth: 320,
      targetHeight: 320,
      saveToPhotoAlbum: true
    };

    // passing options in as a parameter
    Camera.getPicture(options).then(function(imageURI) {
      console.log(imageURI);
      $scope.lastPhoto = imageURI;
    }, function(err) {
      console.err(err);
    });

Im trying above code on android but its not saving to my device, please help

**Comment by mmathys** [comment]
Actually, you have to put the options variable after the second callback, and as a `getPhoto()`-parameter.

```
var options = {
  quality: 75,
  targetWidth: 320,
  targetHeight: 320,
  saveToPhotoAlbum: true
};

// passing options in as a parameter
Camera.getPicture().then(function(imageURI) {
  console.log(imageURI);
  $scope.lastPhoto = imageURI;
}, function(err) {
  console.err(err);
}, options);
```

**Comment by Ionitron** [comment]
Greetings @krismp!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
