### ISSUE TITLE
Cordova plugins not mentioned in README.md

### ISSUE THREAD

**Issue by mmathys** [driftyco/ionic-example-cordova-camera#7]
The required cordova plugins are not mentioned in the Readme.

They are required if you implement the code snippet in another project. However, if you clone this project, the plugins are already installed.

```
org.apache.cordova.camera
org.apache.cordova.console
org.apache.cordova.device
```
I don't know which plugins are actually required for the camera to work.

**Comment by SecuriTeam** [comment]
Only `org.apache.cordova.camera` is required which is the actual plugin code.
Here is the plugin docs: https://github.com/apache/cordova-plugin-camera

**Comment by Ionitron** [comment]
Greetings @mmathys!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
