### ISSUE TITLE
Unable to get base64-encoded string from Photo Library.

### ISSUE THREAD

**Issue by vsandoria** [driftyco/ionic-example-cordova-camera#8]
I am trying to get base64 encoded string of selected video from PhotoLibrary/ 
This gives me file path instead of string data. 

as mentioned is document, I am using "camera.DestinationType.DATA_URL" & "camera.PictureSourceType.PHOTOLIBRARY" and mediaType "camera.MediaType.VIDEO". 

Here is my code....
var options =   {
	    	    	destinationType: 0, 
	    	    	sourceType: 2,
	    	    	mediaType: 1 
	    	    	};
	    	    				
var videoRes = navigator.camera.getPicture(
	    	    					function (videoData) {
	    	    					console.log("videoData");
	    	    					},
	    	    					function (err) {
	    	    						},
	    	    					options);

**Comment by SecuriTeam** [comment]
Base64 is only supported for images, not videos.
Read the highlighted comment below.

---

Camera.MediaType = {
            PICTURE: 0,    // allow selection of still pictures only. DEFAULT. Will return format specified via DestinationType
            VIDEO: 1,      // `allow selection of video only, WILL ALWAYS RETURN FILE_URI`
            ALLMEDIA : 2   // allow selection from all media types
        };

**Comment by Ionitron** [comment]
Greetings @vsandoria!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
